# Generated by Django 4.0 on 2021-12-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=250)),
                ('student_name', models.CharField(max_length=250)),
                ('student_city', models.CharField(max_length=250)),
                ('student_course', models.CharField(max_length=250)),
            ],
        ),
    ]
